name: Build Qt Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Copie de QtMsBuild à partir d'un dossier spécifique dans votre repository (si vous l'avez ajouté)
    - name: Copy QtMsBuild to build directory
      run: |
        mkdir -p C:\QtMsBuild
        copy /Y .\tools\QtMsBuild\* C:\QtMsBuild\

    # Set QtMsBuild environment variable
    - name: Set QtMsBuild environment variable
      run: |
        echo "QTMSBUILD=C:\\QtMsBuild" >> $GITHUB_ENV

    # Installer les dépendances (si nécessaire, comme Visual Studio Build Tools)
    - name: Install Visual Studio Build Tools
      uses: microsoft/setup-msbuild@v1
      with:
        vs-version: '2019'

    - name: Set up Qt environment
      run: |
        echo "QT6_DIR=D:\\a\\Planning-poker\\Qt\\6.7.3\\msvc2019_64" >> $GITHUB_ENV

    # Compilation avec MSBuild
    - name: Build with MSBuild
      run: |
        cmd.exe /c "call \"%ProgramFiles(x86)%\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Auxiliary\\Build\\vcvars64.bat\" && msbuild D:\\a\\Planning-poker\\Planning-poker\\PlanningPoker.sln /p:Configuration=Release /p:Platform=x64"

    # Archiver les fichiers de build (si nécessaire)
    - name: Archive release files
      uses: actions/upload-artifact@v3
      with:
        name: planning-poker-release
        path: D:\a\Planning-poker\build\Release
