name: Build and Deploy Qt Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Qt environment variables for Qt 6.7.3
      - name: Set up Qt 6.7.3 environment variables
        run: |
          echo "##vso[task.setvariable variable=QTDIR]D:\a\Planning-poker\Qt\6.7.3\msvc2019_64"
          echo "##vso[task.setvariable variable=QT_PLUGIN_PATH]D:\a\Planning-poker\Qt\6.7.3\msvc2019_64\plugins"
          echo "##vso[task.setvariable variable=QML2_IMPORT_PATH]D:\a\Planning-poker\Qt\6.7.3\msvc2019_64\qml"
          echo "##vso[task.setvariable variable=PATH]D:\a\Planning-poker\Qt\6.7.3\msvc2019_64\bin;$env:PATH"

      # Install Visual Studio Build Tools
      - name: Set up MSBuild and Visual Studio
        run: |
          echo "Setting up Visual Studio and MSBuild"
          vs_installer_path="C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe"
          if (Test-Path $vs_installer_path) {
            & $vs_installer_path --path-to-vs C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools --add Microsoft.VisualStudio.Workload.VCTools
          }

      # Restore dependencies (if you use NuGet, etc.)
      - name: Restore dependencies
        run: |
          msbuild PlanningPoker.sln /p:Configuration=Release /p:Platform=x64

      # Build the solution with MSBuild
      - name: Build the project
        run: |
          msbuild PlanningPoker.sln /p:Configuration=Release /p:Platform=x64

      # Run windeployqt (if you are building a Qt application with dependencies)
      - name: Run windeployqt
        run: |
          windeployqt .\x64\Release\PlanningPoker.exe

      # Create a release artifact (for uploading or further use)
      - name: Create ZIP of release
        run: |
          powershell Compress-Archive -Path .\x64\Release -DestinationPath ./release.zip

      # Upload the release artifact using the latest version v3
      - name: Upload Release ZIP
        uses: actions/upload-artifact@v3
        with:
          name: planning-poker-release
          path: release.zip
