name: Build and Deploy Qt Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Install Qt (use an installer or download Qt from a reliable source)
      - name: Install Qt
        run: |
          choco install qt5 --version=5.15.2

      # Set up Visual Studio Build Tools
      - name: Set up MSBuild and Visual Studio
        run: |
          echo "Setting up Visual Studio and MSBuild"
          vs_installer_path="C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe"
          if (Test-Path $vs_installer_path) {
            & $vs_installer_path --path-to-vs C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools --add Microsoft.VisualStudio.Workload.VCTools
          }

      # Set up Qt environment variables
      - name: Set up Qt environment variables
        run: |
          echo "Setting up Qt environment variables"
          echo "##vso[task.setvariable variable=QTDIR]C:\Qt\5.15.2\msvc2019_64"
          echo "##vso[task.setvariable variable=QT_PLUGIN_PATH]C:\Qt\5.15.2\msvc2019_64\plugins"
          echo "##vso[task.setvariable variable=QML2_IMPORT_PATH]C:\Qt\5.15.2\msvc2019_64\qml"
          echo "##vso[task.setvariable variable=PATH]C:\Qt\5.15.2\msvc2019_64\bin;$env:PATH"

      # Restore dependencies (if you use NuGet, etc.)
      - name: Restore dependencies
        run: |
          msbuild PlanningPoker.sln /p:Configuration=Release /p:Platform=x64

      # Build the solution with MSBuild
      - name: Build the project
        run: |
          msbuild PlanningPoker.sln /p:Configuration=Release /p:Platform=x64

      # Run windeployqt (if you are building a Qt application with dependencies)
      - name: Run windeployqt
        run: |
          windeployqt .\x64\Release\PlanningPoker.exe

      # Create a release artifact (for uploading or further use)
      - name: Create ZIP of release
        run: |
          powershell Compress-Archive -Path .\x64\Release -DestinationPath ./release.zip

      # Upload the release artifact using the latest version v3
      - name: Upload Release ZIP
        uses: actions/upload-artifact@v3
        with:
          name: planning-poker-release
          path: release.zip
