name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Vérifier le code source
    - name: Checkout code
      uses: actions/checkout@v3

    # Définir les variables d'environnement pour MSBuild et Qt
    - name: Set up Qt environment
      run: |
        # Définir les variables d'environnement pour MSBuild et Qt
        $env:Qt6_DIR="D:\a\Planning-poker\Qt\6.7.3\msvc2019_64"
        $env:QT_PLUGIN_PATH="D:\a\Planning-poker\Qt\6.7.3\msvc2019_64\plugins"
        $env:QML2_IMPORT_PATH="D:\a\Planning-poker\Qt\6.7.3\msvc2019_64\qml"
        
        # Initialiser l'environnement de Visual Studio avec des guillemets échappés
        cmd.exe /c '"C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvars64.bat"'

    # Vérification des prérequis et installation des dépendances Python
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Compiler avec MSBuild
    - name: Build with MSBuild
      run: |
        msbuild D:\a\Planning-poker\Planning-poker\PlanningPoker.sln /p:Configuration=Release /p:Platform=x64
