name: Build Qt Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Verify contents before copying
    - name: List contents of tools directory
      run: |
        Get-ChildItem -Path .\tools\QtMsBuild -Recurse

    # Copy QtMsBuild using PowerShell
    - name: Copy QtMsBuild to expected directory
      shell: powershell
      run: |
        # Making sure the directory exists and copying the necessary files
        md ${{ github.workspace }}\Planning-poker\PlanningPoker\QtMsBuild
        Copy-Item -Path .\tools\QtMsBuild\* -Destination ${{ github.workspace }}\Planning-poker\PlanningPoker\QtMsBuild\ -Recurse -Force

    # Verify the contents after copying
    - name: List contents of destination directory
      run: |
        Get-ChildItem -Path ${{ github.workspace }}\Planning-poker\PlanningPoker\QtMsBuild -Recurse

    # Install Visual Studio Build Tools
    - name: Install Visual Studio Build Tools
      uses: microsoft/setup-msbuild@v1
      with:
        msbuild-architecture: x64

    # Set up Qt environment
    - name: Set up Qt environment
      run: |
        echo "QT6_DIR=D:\\a\\Planning-poker\\Qt\\6.7.3\\msvc2019_64" >> $GITHUB_ENV

    # Build with MSBuild
    - name: Build with MSBuild
      shell: cmd
      run: |
        for /f "tokens=*" %%i in ('"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath -latest') do set InstallDir=%%i
        call "%InstallDir%\VC\Auxiliary\Build\vcvars64.bat" && msbuild D:\a\Planning-poker\Planning-poker\PlanningPoker.sln /p:Configuration=Release /p:Platform=x64

    # Archive release files
    - name: Archive release files
      uses: actions/upload-artifact@v3
      with:
        name: planning-poker-release
        path: D:\a\Planning-poker\build\Release